### ISSUE TITLE
[7/12/2022] - Documentation on how to make blog posts

### ISSUE THREAD

**Issue by RealRichi3** [Open-Science-Community-Saudi-Arabia/OSCSA-en-blog#44]
### Description
Add documentation on how to add blog posts to the [OSCSA Blog](https://oscsa-en-blog.netlify.app/)

This is meant to help newcomers to create a post in the OSCSA https://oscsa-en-blog.netlify.app/. It assumes that they have written a draft and would like to add it to the website. Please make it as easy as possible to newcomers who have limited knowledge in Open source or Quarto or even programming.

**Comment by sandygudie** [comment]
Welldone @RealRichi3 
I will suggest we include the tools(e.g Quarto) and links to docs, installation as a start

**Comment by RealRichi3** [comment]
Alright @sandygudie, i'll add that
